laravel/cashier-mollie

config/cashier.php, src/FirstPayment/FirstPaymentHandler.php
- Fixes #5 .
- Set the default payment method to `null` in the config, so by default it mirrors the Mollie dashboard
=> Some improvements

database/migrations/create_applied_coupons_table.php.stub, database/migrations/create_credits_table.php.stub, database/migrations/create_order_items_table.php.stub, database/migrations/create_orders_table.php.stub, database/migrations/create_redeemed_coupons_table.php.stub, database/migrations/create_subscriptions_table.php.stub
Reverts laravel/cashier-mollie#18
=> Revert "Changed increments to bigIncrements."

database/migrations/create_applied_coupons_table.php.stub, database/migrations/create_credits_table.php.stub, database/migrations/create_order_items_table.php.stub, database/migrations/create_orders_table.php.stub, database/migrations/create_redeemed_coupons_table.php.stub, database/migrations/create_subscriptions_table.php.stub
This pull request is nearly the same as the one before, but this time all `unsignedInteger` columns that refer to id's are changed to `unsignedBigInteger` columns to match the primary columns.
=> Change increments to big increments.

config/cashier.php, src/CashierServiceProvider.php
Was functionally already moved to `config/cashier_plans.php`
=> Remove obsolete config

README.md
Hello,
I added the latest release to the README.md so that people who are following the README will install the latest version.
=> Add latest version to the readme

src/Helpers/helpers.php
Defining the snake_case function should not happen within the check if ends_with exists
As discussed in #54
=> Move snake_case outside of ends_with

README.md, src/Events/SubscriptionCreated.php, src/Events/SubscriptionStarted.php, src/Subscription.php, tests/ManageSubscriptionTest.php, tests/SubscriptionBuilder/FirstPaymentSubscriptionBuilderTest.php
Added support for the SubscriptionCreated Event regarding issue #96
=> #96 Added SubscriptionStarted Event

README.md, src/Events/SubscriptionResumed.php, src/Subscription.php, tests/ManageSubscriptionTest.php, tests/SubscriptionTest.php
Added the SubscriptionResumed event regarding issue #114
=> Added SubscriptionResumed event

README.md
Point to the correct config file in the readme.
=> Use correct file reference

src/Order/OrderItem.php, tests/CashierTest.php, tests/Order/OrderItemTest.php
=> Fix OrderItem due scope

src/FirstPayment/Actions/StartSubscription.php, tests/FirstPayment/Actions/StartSubscriptionTest.php
=> first payment subscription quantity

src/CashierServiceProvider.php, src/FirstPayment/Actions/AddGenericOrderItem.php, src/FirstPayment/Actions/BaseAction.php, src/FirstPayment/Actions/StartSubscription.php, tests/FirstPayment/Actions/StartSubscriptionTest.php
=> Fix first payment subscription quantity

.travis.yml, composer.json, src/CashierServiceProvider.php, tests/Http/Controllers/WebhookControllerTest.php
=> Release v1.11.1

routes/webhooks.php, src/Cashier.php, tests/CashierTest.php
Issue: https://github.com/laravel/cashier-mollie/issues/220
=> webhookUrl and firstPaymentWebhookUrl methods

resources/views/receipt.blade.php
See #240 ("Invoice balance incorrect #240") for more information.
=> Update receipt starting balance

.travis.yml, composer.json, src/Order/Order.php, tests/Order/OrderTest.php
- Laravel 8 support
- Fixed a false error
- Scope paid orders now support "full balance payments"
=> Laravel 8 support and more

src/Order/Order.php
Reverts laravel/cashier-mollie#266
=> Revert "fix: avoid duplicates in order's owner check"

.github/workflows/tests.yaml, composer.json
=> Add PHP 8 ci tests

README.md, src/CashierServiceProvider.php, src/Events/OrderPaymentFailedDueToInvalidMandate.php, src/Order/Order.php, tests/Order/OrderTest.php
=> handle invalid mandate

src/Http/Controllers/FirstPaymentWebhookController.php, src/Order/Order.php
=> Drop refund calls on first payments

config/cashier_coupons.php, src/Coupon/PercentageDiscountHandler.php, tests/Coupon/PercentageCouponTest.php
Added a discount handler for discounts with a percentage
=> Add Percentage Discount Handler
